[env]
term = "xterm-256color"

[window]
decorations = "none"
option_as_alt = "Both"

[font]
size = 14

  [font.normal]
  family = "Hack Nerd Font"
  style = "Regular"

  [font.bold]
  family = "Hack Nerd Font"
  style = "Bold"

  [font.italic]
  family = "Hack Nerd Font"
  style = "Italic"

  [font.offset]
  x = 0
  y = -1

  [font.glyph_offset]
  x = 0
  y = 0

[colors.primary]
background = "#192330"
foreground = "#cdcecf"
dim_foreground = "#aeafb0"
bright_foreground = "#d6d6d7"

[colors.cursor]
text = "#cdcecf"
cursor = "#aeafb0"

[colors.vi_mode_cursor]
text = "#cdcecf"
cursor = "#63cdcf"

[colors.search.matches]
foreground = "#cdcecf"
background = "#3c5372"

[colors.search.focused_match]
foreground = "#cdcecf"
background = "#81b29a"

[colors.footer_bar]
foreground = "#cdcecf"
background = "#29394f"

[colors.hints.start]
foreground = "#cdcecf"
background = "#f4a261"

[colors.hints.end]
foreground = "#cdcecf"
background = "#29394f"

[colors.selection]
text = "#cdcecf"
background = "#2b3b51"

[colors.normal]
black = "#393b44"
red = "#c94f6d"
green = "#81b29a"
yellow = "#dbc074"
blue = "#719cd6"
magenta = "#9d79d6"
cyan = "#63cdcf"
white = "#dfdfe0"

[colors.bright]
black = "#575860"
red = "#d16983"
green = "#8ebaa4"
yellow = "#e0c989"
blue = "#86abdc"
magenta = "#baa1e2"
cyan = "#7ad5d6"
white = "#e4e4e5"

[colors.dim]
black = "#30323a"
red = "#ab435d"
green = "#6e9783"
yellow = "#baa363"
blue = "#6085b6"
magenta = "#8567b6"
cyan = "#54aeb0"
white = "#bebebe"
[[keyboard.bindings]]
key = "Q"
mods = "Command"
action = "Quit"

[[keyboard.bindings]]
key = "V"
mods = "Command"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Command"
action = "Copy"

[[keyboard.bindings]]
key = "Key1"
mods = "Command"
chars = "\u00011"

[[keyboard.bindings]]
key = "Key2"
mods = "Command"
chars = "\u00012"

[[keyboard.bindings]]
key = "Key3"
mods = "Command"
chars = "\u00013"

[[keyboard.bindings]]
key = "Key4"
mods = "Command"
chars = "\u00014"

[[keyboard.bindings]]
key = "Key5"
mods = "Command"
chars = "\u00015"

[[keyboard.bindings]]
key = "Key6"
mods = "Command"
chars = "\u00016"

[[keyboard.bindings]]
key = "Key7"
mods = "Command"
chars = "\u00017"

[[keyboard.bindings]]
key = "Key8"
mods = "Command"
chars = "\u00018"

[[keyboard.bindings]]
key = "Key9"
mods = "Command"
chars = "\u00019"

[[keyboard.bindings]]
key = "T"
mods = "Command"
chars = "\u0001c"

[[keyboard.bindings]]
key = "W"
mods = "Command"
chars = "\u0001x"

[[keyboard.bindings]]
key = "F"
mods = "Control"
chars = "\u0001f"

[[keyboard.bindings]]
key = "O"
mods = "Command"
chars = "\u0001a"

[[keyboard.bindings]]
key = "Home"
chars = "\u001b[H"
mode = "~AppCursor"

[[keyboard.bindings]]
key = "Home"
chars = "\u001b[1~"
mode = "AppCursor"

[[keyboard.bindings]]
key = "End"
chars = "\u001b[F"
mode = "~AppCursor"

[[keyboard.bindings]]
key = "End"
chars = "\u001b[4~"
mode = "AppCursor"

[[keyboard.bindings]]
key = "PageUp"
chars = "\u001b[5~"

[[keyboard.bindings]]
key = "PageDown"
chars = "\u001b[6~"

[[keyboard.bindings]]
key = "Equals"
mods = "Command"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "Minus"
mods = "Command"
action = "DecreaseFontSize"

[[keyboard.bindings]]
key = "Left"
mods = "Shift"
chars = "\u001b[1;2D"

[[keyboard.bindings]]
key = "Left"
mods = "Control"
chars = "\u001b[1;5D"

[[keyboard.bindings]]
key = "Left"
mods = "Alt"
chars = "\u001b[1;3D"

[[keyboard.bindings]]
key = "Left"
chars = "\u001b[D"
mode = "~AppCursor"

[[keyboard.bindings]]
key = "Left"
chars = "\u001bOD"
mode = "AppCursor"

[[keyboard.bindings]]
key = "Right"
mods = "Shift"
chars = "\u001b[1;2C"

[[keyboard.bindings]]
key = "Right"
mods = "Control"
chars = "\u001b[1;5C"

[[keyboard.bindings]]
key = "Right"
mods = "Alt"
chars = "\u001b[1;3C"

[[keyboard.bindings]]
key = "Right"
chars = "\u001b[C"
mode = "~AppCursor"

[[keyboard.bindings]]
key = "Right"
chars = "\u001bOC"
mode = "AppCursor"

[[keyboard.bindings]]
key = "Up"
mods = "Shift"
chars = "\u001b[1;2A"

[[keyboard.bindings]]
key = "Up"
mods = "Control"
chars = "\u001b[1;5A"

[[keyboard.bindings]]
key = "Up"
mods = "Alt"
chars = "\u001b[1;3A"

[[keyboard.bindings]]
key = "Up"
chars = "\u001b[A"
mode = "~AppCursor"

[[keyboard.bindings]]
key = "Up"
chars = "\u001bOA"
mode = "AppCursor"

[[keyboard.bindings]]
key = "Down"
mods = "Shift"
chars = "\u001b[1;2B"

[[keyboard.bindings]]
key = "Down"
mods = "Control"
chars = "\u001b[1;5B"

[[keyboard.bindings]]
key = "Down"
mods = "Alt"
chars = "\u001b[1;3B"

[[keyboard.bindings]]
key = "Down"
chars = "\u001b[B"
mode = "~AppCursor"

[[keyboard.bindings]]
key = "Down"
chars = "\u001bOB"
mode = "AppCursor"

[[keyboard.bindings]]
key = "Tab"
mods = "Shift"
chars = "\u001b[Z"

[[keyboard.bindings]]
key = "F1"
chars = "\u001bOP"

[[keyboard.bindings]]
key = "F2"
chars = "\u001bOQ"

[[keyboard.bindings]]
key = "F3"
chars = "\u001bOR"

[[keyboard.bindings]]
key = "F4"
chars = "\u001bOS"

[[keyboard.bindings]]
key = "F5"
chars = "\u001b[15~"

[[keyboard.bindings]]
key = "F6"
chars = "\u001b[17~"

[[keyboard.bindings]]
key = "F7"
chars = "\u001b[18~"

[[keyboard.bindings]]
key = "F8"
chars = "\u001b[19~"

[[keyboard.bindings]]
key = "F9"
chars = "\u001b[20~"

[[keyboard.bindings]]
key = "F10"
chars = "\u001b[21~"

[[keyboard.bindings]]
key = "F11"
chars = "\u001b[23~"

[[keyboard.bindings]]
key = "F12"
chars = "\u001b[24~"

[[keyboard.bindings]]
key = "Back"
chars = "\u007f"

[[keyboard.bindings]]
key = "Delete"
chars = "\u001b[3~"
mode = "AppKeypad"

[[keyboard.bindings]]
key = "Delete"
chars = "\u001b[P"
mode = "~AppKeypad"

[[keyboard.bindings]]
key = "N"
mods = "Command"
action = "SpawnNewInstance"

