# default statusbar colors

set -g mode-style "fg=#34405a,bg=#aeafb0"
set -g message-style "fg=#34405a,bg=#aeafb0"
set -g message-command-style "fg=#34405a,bg=#aeafb0"
set -g pane-border-style "fg=#aeafb0"
set -g pane-active-border-style "fg=#719cd6"
set -g status "on"
set -g status-justify "left"
set -g status-style "fg=#aeafb0,bg=#34405a"
set -g status-left-length "100"
set -g status-right-length "100"
set -g status-left-style NONE
set -g status-right-style NONE
set -g status-left "#[fg=#fdf6e3,bg=#719cd6,bold] #S #[fg=#719cd6,bg=#34405a,nobold,nounderscore,noitalics]"
set -g status-right "#[fg=#34405a,bg=#34405a,nobold,nounderscore,noitalics]#[fg=#719cd6,bg=#34405a] #{prefix_highlight} #[fg=#859900,bg=#34405a,nobold,nounderscore,noitalics]#[fg=#ffffff,bg=#859900] %Y-%m-%d #[fg=#34405a,bg=#859900,nobold,nounderscore,noitalics]#[fg=#b58900,bg=#34405a]#[fg=#ffffff,bg=#b58900] %I:%M %p #[fg=#34405a,bg=#b58900,nobold,nounderscore,noitalics]#[fg=#719cd6,bg=#34405a,nobold,nounderscore,noitalics]#[fg=#ffffff,bg=#719cd6,bold] #h "

setw -g window-status-activity-style "underscore,fg=#71839b,bg=#34405a"
setw -g window-status-separator ""
setw -g window-status-style "NONE,fg=#ffffff,bg=#34405a"
setw -g window-status-format "#[fg=#34405a,bg=#34405a,nobold,nounderscore,noitalics]#[default] #I  #W #F #[fg=#34405a,bg=#34405a,nobold,nounderscore,noitalics]"
setw -g window-status-current-format "#[fg=#34405a,bg=#cb4b16,nobold,nounderscore,noitalics]#[fg=#fdf6e3,bg=#cb4b16,bold] #I  #W #F #[fg=#cb4b16,bg=#34405a,nobold,nounderscore,noitalics]"
