syntax on
colorscheme gruvbox
set background=dark
set nocompatible              " be iMproved, required
filetype off                  " required
set laststatus=2
set hls
set backspace=indent,eol,start
set mouse=a
set clipboard=unnamed
set number
set relativenumber

let mapleader = "\<Space>"

"Disable preview window on top for YouAutoCompleteMe
set completeopt-=preview

let g:airline_powerline_fonts=1
let g:airline_theme='tomorrow'

set sw=2 ts=2 sts=2
au FileType go setl sw=4 sts=4 ts=4
au FileType swift setl sw=4 sts=4 ts=4

autocmd QuickFixCmdPost *grep* cwindow

"Ctrp
set wildignore+=*/tmp/*,*/vendor/*,*.so,*.swp,*.zip
set expandtab
" This is the default extra key bindings

" Undo
set undofile
set undodir=$HOME/.vim/undo

source ~/dotfiles/vimconfig/filetypes.vim
source ~/dotfiles/vimconfig/go.vim
source ~/dotfiles/vimconfig/ruby.vim
source ~/dotfiles/vimconfig/syntastic.vim 
source ~/dotfiles/vimconfig/fastctrlp.vim
source ~/dotfiles/vimconfig/mappings.vim
source ~/dotfiles/vimconfig/plugins.vim
source ~/dotfiles/vimconfig/visual-selection.vim
"source ~/dotfiles/vimconfig/tab-wrapper.vim
"source ~/dotfiles/vimconfig/fzf.vim
"augroup reload_vimrc " {
    "autocmd!
    "autocmd BufWritePost $MYVIMRC source $MYVIMRC
"augroup END " }
